server:
  port: 8093
  compression:
    enabled: true
    mime-types: "application/json,application/xml,text/html,text/xml,text/plain"
  tomcat:
    compression: on
    compressable-mime-types: "application/json,application/xml,text/html,text/xml,text/plain"

logging:
  file: /tmp/nm-ad-server.log
  level:
    org.springframework.security: INFO
    io.ridesafe.backend: DEBUG
---