server:
  port: 8093
  compression:
    enabled: true
    mime-types: "application/json,application/xml,text/html,text/xml,text/plain"
  tomcat:
    compression: on
    compressable-mime-types: "application/json,application/xml,text/html,text/xml,text/plain"

logging:
  file: /tmp/nm-ad-server.log
  level:
    org.springframework.security: INFO
    io.ridesafe.backend: DEBUG
---

cassandra:
  contact-points: "10.200.0.1"
  port: 9042
  keyspace: "ridesafe"

ridesafe:
  web:
    host: "^http(s)?://(localhost:9\\d{3}|(\\w+-)?(\\w+\\.)?ridesafe\\.io)$"

nm:
  core:
    login-url: "http://nm-core/api/v1/login"
    logout-url: "http://nm-core/api/v1/logout"
    account-url: "http://nm-core/api/v1/account/authorities"